### ISSUE TITLE
Link Shortener

### ISSUE THREAD

**Issue by kodepirate** [ridsuteri/Awesome-Chrome-Extensions#28] opened 2022-03-01 10:41 UTC
Hlo @ridsuteri I would like  to add a **link shortener** in this project under GSSOC-2022.

**Comment by ridsuteri** [comment] 2022-03-01 10:58
great, go ahead @kodepirate :)

**Comment by kodepirate** [comment] 2022-03-03 09:43
This is issue no #28 You have already assigned it to me

**Comment by sceary-expert** [comment] 2022-03-04 06:40
I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903 can you assign me? Please assign me and give some detailed information on what issue you are facing using this link shortener.

**Comment by ridsuteri** [comment] 2022-03-04 11:45
@sceary-expert the issue is fixed by the PR #59

**Closed by ridsuteri** 2022-03-04 11:45 UTC
Labels: GSSoC22
