### ISSUE TITLE
Digital Clock

### ISSUE THREAD

**Issue by Areebah03** [ridsuteri/Awesome-Chrome-Extensions#275] opened 2022-05-14 04:15 UTC
### Is your feature request related to a problem? Please describe.

We don't have a digital calculator.

### Describe the solution you'd like.

I want to add a digital calculator with awesome css effect.

### Describe alternatives you've considered.

I will add digital calculator to this project.

### Add any other context or screenshots about the feature request here.

![8](https://user-images.githubusercontent.com/85051124/168410345-176c6711-5784-47e9-aa7d-a16b34dd1d1f.png)

**Comment by Akshima-Ghai** [comment] 2022-05-14 04:34
issue assigned @Areebah03

**Comment by navyasharma0203** [comment] 2022-05-15 19:28
Hi there! I would like to work on this issue. Can you assign this to me? I have really good and responsive designs....

**Comment by ridsuteri** [comment] 2022-05-17 06:36
@navyasharma0203 the issue is assigned and PR is also open hence can't assign you the same issue :(

**Closed** 2022-05-20 04:14 UTC
Labels: GSSoC22
