### ISSUE TITLE
Title: Maths Addition Game

### ISSUE THREAD

**Issue by kalashvasaniya** [ridsuteri/Awesome-Chrome-Extensions#90] opened 2022-03-09 06:30 UTC
### Is your feature request related to a problem? Please describe.

Making Maths Addition Game.

### Describe the solution you'd like.

I make this game using HTML, CSS, JS.

### Describe alternatives you've considered.

Maths Addition Game.

**Comment by goyalsaksh** [comment] 2022-03-11 14:30
Hello , I am gssoc contributor , can you assign it to me

**Comment by ridsuteri** [comment] 2022-03-12 03:52
@goyalsaksh the issue is already assigned, if @kalashvasaniya fails to submit a PR within a few days, it will be assigned to you :)

**Closed** 2022-03-13 09:29 UTC
Labels: GSSoC22
